version: '3.5'

services:
  boldbi:
   container_name: boldbi
   image: syncfusion/boldbi
   restart: always
   ports:
     - 8085:80
   networks:
     - boldbi
   volumes:
     - boldbi_data:/application/app_data
    
networks:
  boldbi:
  
volumes:
  boldbi_data:

